import 'dotenv/config';
import {
  analyzeTokenWalletIntelligence,
  expandWalletCapitalGraph,
  prisma,
  scanTrackedTokenActivations,
  type ChainId
} from '@flowradar/db';

type PilotResult = { status: 'completed'; result: unknown } | { status: 'honest_empty'; reason: string } | { status: 'failed'; error: string };
const evmChains: ChainId[] = ['ETHEREUM', 'BASE', 'ARBITRUM', 'BSC'];

try {
  const [solanaCandidate, anyCandidate, solanaEvent, evmEvent, bridgeCorrelation, latestEvent, latestTrackerRun] = await Promise.all([
    prisma.tokenTopPnlCandidate.findFirst({ where: { chain: 'SOLANA' }, orderBy: [{ confidence: 'desc' }, { updatedAt: 'desc' }] }),
    prisma.tokenTopPnlCandidate.findFirst({ orderBy: [{ confidence: 'desc' }, { updatedAt: 'desc' }] }),
    prisma.massTransactionEvent.findFirst({
      where: { chain: 'SOLANA', kind: { in: ['native_transfer', 'token_transfer', 'bridge_source'] }, status: { not: 'failed' } },
      orderBy: [{ ts: 'desc' }, { eventId: 'desc' }]
    }),
    prisma.massTransactionEvent.findFirst({
      where: { chain: { in: evmChains }, kind: { in: ['native_transfer', 'token_transfer', 'bridge_source'] }, status: { not: 'failed' } },
      orderBy: [{ ts: 'desc' }, { eventId: 'desc' }]
    }),
    prisma.massBridgeCorrelation.findFirst({ where: { status: 'verified' }, orderBy: { correlatedAt: 'desc' } }),
    prisma.massTransactionEvent.findFirst({ orderBy: [{ observedAt: 'desc' }, { eventId: 'desc' }] }),
    prisma.massTrackerRun.findFirst({ orderBy: { startedAt: 'desc' } })
  ]);

  const tokenSeed = solanaCandidate ?? anyCandidate;
  const token: PilotResult = tokenSeed
    ? await capture(() => analyzeTokenWalletIntelligence(prisma, { chain: tokenSeed.chain, tokenAddress: tokenSeed.mint, topLimit: 10 }))
    : { status: 'honest_empty', reason: 'No persisted top-PnL token candidate exists in the real local dataset.' };

  const solanaWalletSeed = solanaEvent?.actorAddress ?? solanaEvent?.fromAddress
    ?? (await prisma.wallet.findFirst({ where: { chain: 'SOLANA' }, orderBy: { lastActiveAt: 'desc' } }))?.address;
  const solanaWallet: PilotResult = solanaWalletSeed
    ? await capture(() => expandWalletCapitalGraph(prisma, { chain: 'SOLANA', walletAddress: solanaWalletSeed, maxDepth: 3, maxNodes: 100, maxEventsPerNode: 500 }))
    : { status: 'honest_empty', reason: 'No real Solana wallet exists in the local observation dataset.' };

  const evmWalletSeed = evmEvent?.actorAddress ?? evmEvent?.fromAddress
    ?? (await prisma.wallet.findFirst({ where: { chain: { in: evmChains } }, orderBy: { lastActiveAt: 'desc' } }))?.address;
  const evmWalletChain = evmEvent?.chain
    ?? (evmWalletSeed ? (await prisma.wallet.findFirst({ where: { address: evmWalletSeed, chain: { in: evmChains } }, select: { chain: true } }))?.chain : null);
  const evmWallet: PilotResult = evmWalletSeed && evmWalletChain
    ? await capture(() => expandWalletCapitalGraph(prisma, { chain: evmWalletChain, walletAddress: evmWalletSeed, maxDepth: 3, maxNodes: 100, maxEventsPerNode: 500 }))
    : { status: 'honest_empty', reason: 'No real EVM wallet exists in the local observation dataset.' };

  let bridgeCluster: PilotResult = { status: 'honest_empty', reason: 'No verified official bridge correlation exists in the real local dataset.' };
  if (bridgeCorrelation) {
    const source = await prisma.massTransactionEvent.findUnique({ where: { eventId: bridgeCorrelation.sourceEventId } });
    const bridgeWallet = source?.actorAddress ?? source?.fromAddress;
    bridgeCluster = source && bridgeWallet
      ? await capture(() => expandWalletCapitalGraph(prisma, { chain: source.chain, walletAddress: bridgeWallet, maxDepth: 3, maxNodes: 150, maxEventsPerNode: 1_000 }))
      : { status: 'honest_empty', reason: 'Verified bridge correlation exists but its source receipt is unavailable.' };
  }

  const activationNow = latestEvent ? new Date(latestEvent.observedAt.getTime() + 1) : new Date();
  const activation = await capture(() => scanTrackedTokenActivations(prisma, {
    since: new Date(activationNow.getTime() - 30 * 86_400_000),
    now: activationNow,
    maxTrackedWallets: 50_000,
    maxBuyEvents: 100_000
  }));

  const persisted = await Promise.all([
    prisma.tokenWalletIntelligence.count(),
    prisma.walletFlowRelationship.count(),
    prisma.trackedTokenActivationAlert.count({ where: { status: 'active' } }),
    prisma.trackedTokenActivationAlert.count({ where: { status: 'invalidated' } }),
    prisma.trackedActivationScanRun.count(),
    prisma.monitoringSubscription.count({ where: { active: true } })
  ]);
  const report = {
    generatedAt: new Date().toISOString(),
    datasetTruth: 'existing real local rows only; no synthetic transactions or alerts were generated by this pilot',
    seeds: {
      token: tokenSeed ? { chain: tokenSeed.chain, tokenAddress: tokenSeed.mint } : null,
      solanaWallet: solanaWalletSeed ?? null,
      evmWallet: evmWalletSeed && evmWalletChain ? { chain: evmWalletChain, address: evmWalletSeed } : null,
      bridgeCorrelationId: bridgeCorrelation?.correlationId ?? null
    },
    pilots: { token, solanaWallet, evmWallet, bridgeCluster, activation },
    persisted: {
      tokenWalletIntelligence: persisted[0],
      walletFlowRelationships: persisted[1],
      activeActivationAlerts: persisted[2],
      invalidatedActivationAlerts: persisted[3],
      activationScanRuns: persisted[4],
      activeMonitoringSubscriptions: persisted[5]
    },
    latestMassTrackerOperationalReceipt: latestTrackerRun ? {
      runId: latestTrackerRun.id,
      status: latestTrackerRun.status,
      inputEvents: latestTrackerRun.inputEvents,
      persistedEvents: latestTrackerRun.persistedEvents,
      batches: latestTrackerRun.batches,
      retryAttempts: latestTrackerRun.retryAttempts,
      providerErrors: latestTrackerRun.providerErrors,
      peakHeapBytes: latestTrackerRun.peakHeapBytes.toString(),
      throughputPerSec: latestTrackerRun.throughputPerSec
    } : null
  };
  console.log(JSON.stringify(report, null, 2));
} finally {
  await prisma.$disconnect();
}

async function capture(run: () => Promise<unknown>): Promise<PilotResult> {
  try {
    return { status: 'completed', result: await run() };
  } catch (error) {
    return { status: 'failed', error: error instanceof Error ? error.message : String(error) };
  }
}
